### ISSUE TITLE
Add support for web lit tagging via web literacy client

### ISSUE THREAD

**Issue by brettgaylor** [mozilla/webmaker-kits-builder#11]
https://github.com/mozilla/web-literacy-client

**Comment by fuzzyfox** [comment]
@brettgaylor I'm guessing this the method for tagging weblit skills we spoke about? Should this be kind of autosuggest just be for the weblit skills or should we integrate it w/ the context tags too?

I'm thinking it might be good to separate them out but not sure how it would be justified in the UI to have two sets of tags that look like the same thing... Maybe keeping it all together as one auto suggest, and then having a prompt to use weblit-tags?

**Comment by fuzzyfox** [comment]
Autocomplete for known tags in makeapi: https://cade.makes.org/thimble/makeapi-tag-suggestions-demo-prod

**Comment by fuzzyfox** [comment]
Worked on this ([fuzzyfox/webmaker-tagger](https://github.com/fuzzyfox/webmaker-tagger)) which might help solve this along w/ better tagging completion for contextual tags too.

It combines some of the autocomplete from Thimble for tags, with the weblit-client.

**Comment by fuzzyfox** [comment]
hey @brettgaylor just wondering if the current tagging in the [builder](http://kitbuilder.webmakerprototypes.org) satisfies this need. UX is to change a bit still.

**Comment by fuzzyfox** [comment]
marking this as done, file new issue for ux if/when needed
