### ISSUE TITLE
Create build for user testing

### ISSUE THREAD

**Issue by keyboardkat** [mozilla/webmaker-kits-builder#18]
We need an **easily-viewable build** of Kit Builder to share with some sample educators and get their feedback. 

Ideally, this would mean putting it online somewhere so that users without a knowledge of Github can view and comment using Red Pen or another notation tool, and so that I can draft a few user testing scripts to prompt that feedback early in the process.

**Comment by keyboardkat** [comment]
@Pomax @fuzzyfox ping ;) (this was done at Pomax's behest)

**Comment by fuzzyfox** [comment]
how does http://kitbuilder.webmakerprototypes.org work for you?

**Comment by simonwex** [comment]
@keyboardkat see url above, closing issue.

**Comment by keyboardkat** [comment]
This is great, thanks. Let me know when it's at a point that you'd like some initial feedback from educators.

**Comment by keyboardkat** [comment]
This now done.
