### ISSUE TITLE
Add the ability to seach for activities to use in kit

### ISSUE THREAD

**Issue by fuzzyfox** [mozilla/webmaker-kits-builder#2]
Make use of the makeapi to search for activities within the system and allow the user to add discovered activities to their kit, and sort as needed.

**Comment by iamjessklein** [comment]
I wonder if this could leverage the existing playlist maker that cade prototyped.

**Comment by fuzzyfox** [comment]
That could be a really interesting way to store the activities, have KB do the searching (w/ an OER focus), send the ordered results into the api as a list (the backend to what cade built for the list maker), and then load this into the kit as needed.

@cadecairos – how well do you think that would work w/ a modular collection of activities? Is it possible to switch out items in a list relatively easily?
