### ISSUE TITLE
As an [educator], I want to be able to add a list of steps when creating a new activity

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#27]
MVP is plain text

It starts with one step and you can add more, and we need to wireframe the edit modes.

![screen shot 2014-05-14 at 5 55 36 pm](https://cloud.githubusercontent.com/assets/1824988/2977987/8dc19d72-dbb2-11e3-9a95-cef1a410c67c.png)

**Comment by fuzzyfox** [comment]
Hmmm... this to me looks like activity creation. Not sure if this fits for MVP, however the same basic code for the **kit**builder should work for activities.

**Comment by ZeeJab** [comment]
MVP implementation: 
![screen shot 2014-07-08 at 12 59 59 pm](https://cloud.githubusercontent.com/assets/1824988/3513320/6efb326a-06c1-11e4-875b-6d5b25a4b921.png)
