### ISSUE TITLE
As an [educator], I want to be able to format the steps in my activity.

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#28]
For the MVP, users should be able to enter Markdown into the step editor and get a preview immediately of what it would look like. We should be careful to sanitize this since by default all HTML is valid Markdown.

**Comment by fuzzyfox** [comment]
Again this is more activity related than kit related.

**Comment by fuzzyfox** [comment]
This is mostly overridden by us wanting to control the design of activities in kits as well as by the ability to search for activities.
