### ISSUE TITLE
As an [educator], I want to be able to select from popular tags to apply to my kit

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#29]
![screen shot 2014-05-14 at 6 07 46 pm](https://cloud.githubusercontent.com/assets/1824988/2978080/376ade46-dbb4-11e3-803b-50ce04556bd6.png)

**Comment by fuzzyfox** [comment]
This should work for both kits and activities. I'd expand this out to also include webliteracy tags
