### ISSUE TITLE
As an [educator], I want to be able to able to search for more tags and add them to my kit

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#30]
![screen shot 2014-05-14 at 6 08 53 pm](https://cloud.githubusercontent.com/assets/1824988/2978087/5f689b22-dbb4-11e3-9c3e-49e3f677df0b.png)

**Comment by fuzzyfox** [comment]
can search and selection be combined in a similar manner to how thimble + popcornmaker do tags?
