### ISSUE TITLE
As an [educator], I want to be able to create new tags while I'm creating an kit.

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#31]
Question: Are tags deletable after they get created? 

![screen shot 2014-05-14 at 6 10 40 pm](https://cloud.githubusercontent.com/assets/1824988/2978103/9ce5bc14-dbb4-11e3-98f7-cb3291c8c1c1.png)

**Comment by fuzzyfox** [comment]
see comments on issues #29 and #30
