### ISSUE TITLE
As an [educator], I want to be shown a list of related activities that I can choose to show to my participants.

### ISSUE THREAD

**Issue by ZeeJab** [mozilla/webmaker-kits-builder#33]
Question: Is MVP two activities?

![screen shot 2014-05-14 at 6 18 52 pm](https://cloud.githubusercontent.com/assets/1824988/2978174/c1f6c4d4-dbb5-11e3-89a7-af4bd55b0025.png)

**Comment by fuzzyfox** [comment]
To my understanding this is more about being able to find activities to include in a kit, and sort them into an agenda.

Maybe the story should be:

"As an [educator], I want to be be able to search for activities that help my learners achieve their learning objectives, and include this in my kit."

**Comment by simonwex** [comment]
@ZeeJab I don't fully understand this one, do you mind expanding on it a bit?

**Comment by ZeeJab** [comment]
@simonwex I originally thought this was meant to show you a list of related activities [based on tags maybe?] that would be shown to the user and they could add to their kit? But is it a searchable list of activities as per ^ @fuzzyfox ?
