### ISSUE TITLE
deploy kitbuilder to wmproto.o

### ISSUE THREAD

**Issue by fuzzyfox** [mozilla/webmaker-kits-builder#36]
- [x] Approved PR #34 – to add tagging to hostit branch (for integration deployment)
- [x] Approved PR #35 – to get rid of the temp hostit branch
- [ ] Kill hostit branch (its a temp branch anyway)
- [x] merge develop into master for wm training week beginning
- [x] push master to heroku (kit-builder.heroku...)
- [x] dns for kitbuilder.wmproto.o sorted (see bug https://bugzilla.mozilla.org/show_bug.cgi?id=1011595)

**Comment by fuzzyfox** [comment]
Making point 2 (#35) dependent on #37

**Comment by ZeeJab** [comment]
This seems to have been resolved via the merge made for #37
Closing.
