### ISSUE TITLE
Publish kits into makeapi

### ISSUE THREAD

**Issue by fuzzyfox** [mozilla/webmaker-kits-builder#4]
Quick win route = as a Thimble make.

**Comment by Pomax** [comment]
This is probably solved with how #4 is (presumably) best solved.

**Comment by fuzzyfox** [comment]
@Pomax ? This is #4.
I think this is dependent on what we define publish to mean. I've separated out what I think works best for keeping both the idea of being able to have full remix potential for kits post creation as well as speed of getting content into the ecosystem in #9.

This issue is more about taking the stub created by the builder, and just publishing it so that the system thinks it is a Thimble project, that is tagged "teach-kit"

**Comment by Pomax** [comment]
hurray for the wrong link! I meant #7
