### ISSUE TITLE
Hold bug triage/update meeting

### ISSUE THREAD

**Issue by keyboardkat** [mozilla/webmaker-kits-builder#44]
Meeting goals: Update team on @fuzzyfox's progress working within the code itself, and on related discussions held last two weeks of May. Sync up re: issue triage, and next steps to get this shipped.

**Comment by keyboardkat** [comment]
Now scheduled for _13:00 BST/ 11:00EST/ 8:00PST Thurs 5 June_.
Meeting notes will go here: https://etherpad.mozilla.org/teachingkitwizard

**Comment by simonwex** [comment]
Yay!

**Comment by iamjessklein** [comment]
yay for getting it on the calendar :calendar:
